<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Helix Toolkit is a collection of 3D components for .NET.</Description>
    <PackageTags>3D</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
