<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Helix Toolkit is a collection of 3D components for .NET. This package is based on AssimpNet. Provides Assimp Import/Export for HelixToolkit.</Description>
    <PackageTags>3D Assimp</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpAssimp" Version="6.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelixToolkit\HelixToolkit.csproj" />
  </ItemGroup>

</Project>
