<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Helix Toolkit is a collection of 3D components for .NET. This package is based on WPF and SharpDX.</Description>
    <PackageTags>3D Maths</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelixToolkit\HelixToolkit.csproj" />
  </ItemGroup>

</Project>
